#!/bin/bash

# Compiling with make file
make -C src/mall-costumer-dataset

# For valgrind execution
# OMP_NUM_THREADS=1 valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s ./src/mall-costumer-dataset/out 201 5 data/Mall_Customers.csv 10 

CORES=6

for p in `seq ${CORES}`; do
    for rep in `seq 5`; do 
        OMP_NUM_THREADS=$p ./src/mall-costumer-dataset/out 201 5 data/Mall_Customers.csv 10
        echo ""
    done
    echo "-----------------------------------------------------------"
done

make clean -C src/mall-costumer-dataset
