#!/bin/bash

# Compiling with make file
make -C src/house-dataset

CORES=8

EXEC=./src/house-dataset/out
INPUT_DATA=data/house_pre.csv
COLS=3

# Strong Scaling

ROWS=20641 # Real number of rows in dataset

echo "Strong Scaling"
echo ""

for p in `seq ${CORES}`; do
    echo "Threads: $p"
    echo ""
    for rep in `seq 3`; do 
        OMP_NUM_THREADS=$p $EXEC $ROWS $COLS $INPUT_DATA
        echo "-----------------------------------------------------------"
    done
    echo ""
done

# # Weak Scaling
# echo "Weak Scaling"
# echo ""

# MIN_ROWS=2500 #Baseline 
# #Maximum values reached with 8 CORES: 20.000

# for p in `seq ${CORES}`; do
#     echo "Threads: $p"
#     echo ""

#     PROB_SIZE=`echo "$(($p * $MIN_ROWS))"` 
#     echo "Number of rows: ${PROB_SIZE}"
#     for rep in `seq 3`; do 
#         OMP_NUM_THREADS=$p $EXEC $PROB_SIZE $COLS $INPUT_DATA
#         echo "-----------------------------------------------------------"
#     done
#     echo ""
# done

make clean -C src/house-dataset