#!/bin/bash

# Compiling with make file
make -C src/mall-costumer-dataset

EXEC=./src/mall-costumer-dataset/out
INPUT_DATA=data/Mall_Customers.csv
ROWS=201
COLS=5
CLUSTERS=10

CORES=6

for p in `seq ${CORES}`; do
    echo "Threads: $p"
    echo ""
    for rep in `seq 5`; do 
        OMP_NUM_THREADS=$p ${EXEC} ${ROWS} ${COLS} ${INPUT_DATA} ${CLUSTERS}
        echo ""
    done
    echo "-----------------------------------------------------------"
done

make clean -C src/mall-costumer-dataset
