#!/bin/bash

# Compiling with make file
make -C src/house-dataset

# If you want to use valgrind
# Keep in mind it will take a lot of time
# OMP_NUM_THREADS=1 valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes -s ./src/housing-dataset/out 20641 9 data/housing.csv

REAL_NUM_ROWS=20641
ROWS=10000
COLS=3

CORES=8

for p in `seq ${CORES}`; do
    for rep in `seq 3`; do 
        OMP_NUM_THREADS=$p ./src/house-dataset/out ${REAL_NUM_ROWS} ${COLS} data/house_pre.csv
        echo "-----------------------------------------------------------"
    done
    echo ""
done

make clean -C src/house-dataset